### ISSUE TITLE
the predicted values of the trained LR model in the source code are all 0

### ISSUE THREAD

**Issue by lyh02** [xj231/featureinference-vfl#1]
Hello, I have a question. It seems that the predicted values of the trained LR model in the source code are all 0. Is this data set unreasonable

**Comment by xinjianluo** [comment]
> Hello, I have a question. It seems that the predicted values of the trained LR model in the source code are all 0. Is this data set unreasonable

Hi, it could be the reason that the training dataset is severely biased, e.g., 80% instances are labeled as 0 and 20% instances are labeled as 1 (in this case, the model can simply achieve 80% accuracy by always predicting 0). So maybe you need to preprocess the training dataset to reduce the bias if you want to achieve a better result.

By the way, the model outputs do not influence the attack results. Because the attack is based on the memory nature of the model itself (models tend to remember the distributions of the training datasets).
